aliyun:
    oss:
        accessKeyId: xxxxxxxxx
        accessKeySecret: xxxxxxxxx
        bucketName: kdl-you
        endpoint: https://oss-cn-wuhan-lr.aliyuncs.com
mybatis:
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 426255
        url: jdbc:mysql://localhost:3306/bookseller
        username: root
    servlet:
        multipart:
            max-file-size: 20MB
            max-request-size: 100MB
